In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from model import GPT

In [3]:
wei = torch.randn(3, 5, 5)
wei.shape

torch.Size([3, 5, 5])

In [7]:
tril = torch.tril(torch.ones(5, 5))

In [12]:
wei =wei.masked_fill(tril == 0, float("-inf"))

In [13]:
F.softmax(wei, dim=-1)

tensor([[[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5008, 0.4992, 0.0000, 0.0000, 0.0000],
         [0.1979, 0.4119, 0.3902, 0.0000, 0.0000],
         [0.1724, 0.0359, 0.1038, 0.6878, 0.0000],
         [0.0566, 0.0401, 0.0164, 0.8382, 0.0487]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.3573, 0.6427, 0.0000, 0.0000, 0.0000],
         [0.1295, 0.6928, 0.1777, 0.0000, 0.0000],
         [0.0296, 0.4268, 0.1341, 0.4095, 0.0000],
         [0.0833, 0.4901, 0.1910, 0.0259, 0.2096]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.8537, 0.1463, 0.0000, 0.0000, 0.0000],
         [0.3919, 0.3498, 0.2583, 0.0000, 0.0000],
         [0.4016, 0.3612, 0.1038, 0.1334, 0.0000],
         [0.4200, 0.0988, 0.0754, 0.1748, 0.2309]]])

In [15]:
key = torch.randn(3, 5, 10)
query = torch.randn(3, 5, 10)

key.transpose(-2, -1).shape

torch.Size([3, 10, 5])

In [16]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
idx = torch.randint(0, 10, (3, 5))
idx

tensor([[4, 6, 3, 4, 7],
        [7, 4, 5, 9, 6],
        [0, 7, 1, 7, 5]])

In [28]:
idx[:, -9:]

tensor([[4, 6, 3, 4, 7],
        [7, 4, 5, 9, 6],
        [0, 7, 1, 7, 5]])

In [2]:
gpt = GPT()

In [4]:
input = torch.randint(0, 5, (1, 11), dtype=torch.long)
input

tensor([[3, 2, 4, 0, 4, 2, 2, 3, 1, 1, 1]])

In [7]:
gpt.generate(input, 100)

tensor([[ 3,  2,  4,  0,  4,  2,  2,  3,  1,  1,  1, 27, 19, 61, 19, 78, 23, 20,
         58, 26, 74, 53, 26, 29, 57, 53, 61, 37, 14, 71,  5, 44,  6, 98, 60, 56,
          5,  5, 10, 30, 48, 48, 44, 72, 52, 82,  6, 32, 27, 91, 86, 43,  7, 48,
         55,  0, 12, 38, 69, 24, 89, 80, 56, 31, 52, 80, 73, 57, 37, 48, 85, 20,
         75, 80, 71, 73, 25,  2,  7, 89, 60, 67, 88, 71,  8, 44, 24, 42, 76, 10,
         52,  5, 84, 82, 61, 42, 95, 78, 19, 87, 81,  5, 26,  5, 76, 38, 87, 74,
         52,  0, 89]])